// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: Mysql/Options/MysqlOptions.proto

package pboptions

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Type 索引类型
type Type int32

const (
	// T_UNK 索引类型未知
	Type_T_UNK Type = 0
	// T_PKI 索引类型为主键
	Type_T_PKI Type = 1
	// T_FTI 索引类型为全文索引
	Type_T_FTI Type = 2
	// T_UII 索引类型为唯一索引
	Type_T_UII Type = 3
	// T_NII 索引类型为普通索引
	Type_T_NII Type = 4
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "T_UNK",
		1: "T_PKI",
		2: "T_FTI",
		3: "T_UII",
		4: "T_NII",
	}
	Type_value = map[string]int32{
		"T_UNK": 0,
		"T_PKI": 1,
		"T_FTI": 2,
		"T_UII": 3,
		"T_NII": 4,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_Mysql_Options_MysqlOptions_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_Mysql_Options_MysqlOptions_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_Mysql_Options_MysqlOptions_proto_rawDescGZIP(), []int{0}
}

// protoc-gen-mysql的File
type MysqlFile struct {
	state         protoimpl.MessageState  `xorm:"-"`
	sizeCache     protoimpl.SizeCache     `xorm:"-"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
}

func (x *MysqlFile) Reset() {
	*x = MysqlFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mysql_Options_MysqlOptions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MysqlFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlFile) ProtoMessage() {}

func (x *MysqlFile) ProtoReflect() protoreflect.Message {
	mi := &file_Mysql_Options_MysqlOptions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlFile.ProtoReflect.Descriptor instead.
func (*MysqlFile) Descriptor() ([]byte, []int) {
	return file_Mysql_Options_MysqlOptions_proto_rawDescGZIP(), []int{0}
}

// protoc-gen-mysql的Method
type MysqlMethod struct {
	state         protoimpl.MessageState  `xorm:"-"`
	sizeCache     protoimpl.SizeCache     `xorm:"-"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
}

func (x *MysqlMethod) Reset() {
	*x = MysqlMethod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mysql_Options_MysqlOptions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MysqlMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlMethod) ProtoMessage() {}

func (x *MysqlMethod) ProtoReflect() protoreflect.Message {
	mi := &file_Mysql_Options_MysqlOptions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlMethod.ProtoReflect.Descriptor instead.
func (*MysqlMethod) Descriptor() ([]byte, []int) {
	return file_Mysql_Options_MysqlOptions_proto_rawDescGZIP(), []int{1}
}

// Index 用于描述一个索引
type Index struct {
	state         protoimpl.MessageState  `xorm:"-"`
	sizeCache     protoimpl.SizeCache     `xorm:"-"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`

	// IndexType 索引类型
	IndexType Type `protobuf:"varint,1,opt,name=IndexType,proto3,enum=Mysql.Options.Type" json:"IndexType,omitempty" xorm:"ENUM('T_UNK','T_PKI','T_FTI','T_UII','T_NII') notnull default 'T_UNK' 'IndexType'"`
	// IndexField 索引字段
	IndexField []string `protobuf:"bytes,2,rep,name=IndexField,proto3" json:"IndexField,omitempty" xorm:"json notnull 'IndexField'"`
	// Comment 索引注释
	Comment string `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty" xorm:"VARCHAR(255) notnull default('') 'Comment'"`
}

func (x *Index) Reset() {
	*x = Index{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mysql_Options_MysqlOptions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_Mysql_Options_MysqlOptions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_Mysql_Options_MysqlOptions_proto_rawDescGZIP(), []int{2}
}

func (x *Index) GetIndexType() Type {
	if x != nil {
		return x.IndexType
	}
	return Type_T_UNK
}

func (x *Index) GetIndexField() []string {
	if x != nil {
		return x.IndexField
	}
	return nil
}

func (x *Index) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// protoc-gen-mysql的Message
type MysqlMessage struct {
	state         protoimpl.MessageState  `xorm:"-"`
	sizeCache     protoimpl.SizeCache     `xorm:"-"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`

	// Commment 注释
	Comment string `protobuf:"bytes,1,opt,name=Comment,proto3" json:"Comment,omitempty" xorm:"VARCHAR(255) notnull default('') 'Comment'"`
	// Engine 引擎,如果不填,默认为innodb
	Engine string `protobuf:"bytes,2,opt,name=Engine,proto3" json:"Engine,omitempty" xorm:"VARCHAR(255) notnull default('') 'Engine'"`
	// Character 字符集,默认为utf8mb4
	Character string `protobuf:"bytes,3,opt,name=Character,proto3" json:"Character,omitempty" xorm:"VARCHAR(255) notnull default('') 'Character'"`
	// Collate 默认为utf8mb4_general_ci
	Collate string `protobuf:"bytes,4,opt,name=Collate,proto3" json:"Collate,omitempty" xorm:"VARCHAR(255) notnull default('') 'Collate'"`
	// RowFormat 默认为Dynamic
	RowFormat string `protobuf:"bytes,5,opt,name=RowFormat,proto3" json:"RowFormat,omitempty" xorm:"VARCHAR(255) notnull default('') 'RowFormat'"`
	// Indexs 索引
	Indexs []*Index `protobuf:"bytes,6,rep,name=Indexs,proto3" json:"Indexs,omitempty" xorm:"json notnull 'Indexs'"`
	// Database 数据库名称
	Database string `protobuf:"bytes,7,opt,name=Database,proto3" json:"Database,omitempty" xorm:"VARCHAR(255) notnull default('') 'Database'"`
}

func (x *MysqlMessage) Reset() {
	*x = MysqlMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mysql_Options_MysqlOptions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MysqlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlMessage) ProtoMessage() {}

func (x *MysqlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Mysql_Options_MysqlOptions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlMessage.ProtoReflect.Descriptor instead.
func (*MysqlMessage) Descriptor() ([]byte, []int) {
	return file_Mysql_Options_MysqlOptions_proto_rawDescGZIP(), []int{3}
}

func (x *MysqlMessage) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *MysqlMessage) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *MysqlMessage) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *MysqlMessage) GetCollate() string {
	if x != nil {
		return x.Collate
	}
	return ""
}

func (x *MysqlMessage) GetRowFormat() string {
	if x != nil {
		return x.RowFormat
	}
	return ""
}

func (x *MysqlMessage) GetIndexs() []*Index {
	if x != nil {
		return x.Indexs
	}
	return nil
}

func (x *MysqlMessage) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

// protoc-gen-mysql的service
type MysqlService struct {
	state         protoimpl.MessageState  `xorm:"-"`
	sizeCache     protoimpl.SizeCache     `xorm:"-"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
}

func (x *MysqlService) Reset() {
	*x = MysqlService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mysql_Options_MysqlOptions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MysqlService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlService) ProtoMessage() {}

func (x *MysqlService) ProtoReflect() protoreflect.Message {
	mi := &file_Mysql_Options_MysqlOptions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlService.ProtoReflect.Descriptor instead.
func (*MysqlService) Descriptor() ([]byte, []int) {
	return file_Mysql_Options_MysqlOptions_proto_rawDescGZIP(), []int{4}
}

// protoc-gen-mysql 的service
type MysqlField struct {
	state         protoimpl.MessageState  `xorm:"-"`
	sizeCache     protoimpl.SizeCache     `xorm:"-"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`

	// Commment 注释
	Comment string `protobuf:"bytes,1,opt,name=Comment,proto3" json:"Comment,omitempty" xorm:"VARCHAR(255) notnull default('') 'Comment'"`
	// AutoIncr 是否自增
	AutoIncr bool `protobuf:"varint,2,opt,name=AutoIncr,proto3" json:"AutoIncr,omitempty" xorm:"TINYINT(1) unsigned notnull default(0) 'AutoIncr'"`
	// IsNull 是否为NULL
	IsNULL bool `protobuf:"varint,3,opt,name=IsNULL,proto3" json:"IsNULL,omitempty" xorm:"TINYINT(1) unsigned notnull default(0) 'IsNULL'"`
	// Default 默认值
	Default string `protobuf:"bytes,4,opt,name=Default,proto3" json:"Default,omitempty" xorm:"VARCHAR(255) notnull default('') 'Default'"`
}

func (x *MysqlField) Reset() {
	*x = MysqlField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Mysql_Options_MysqlOptions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MysqlField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlField) ProtoMessage() {}

func (x *MysqlField) ProtoReflect() protoreflect.Message {
	mi := &file_Mysql_Options_MysqlOptions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlField.ProtoReflect.Descriptor instead.
func (*MysqlField) Descriptor() ([]byte, []int) {
	return file_Mysql_Options_MysqlOptions_proto_rawDescGZIP(), []int{5}
}

func (x *MysqlField) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *MysqlField) GetAutoIncr() bool {
	if x != nil {
		return x.AutoIncr
	}
	return false
}

func (x *MysqlField) GetIsNULL() bool {
	if x != nil {
		return x.IsNULL
	}
	return false
}

func (x *MysqlField) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

var File_Mysql_Options_MysqlOptions_proto protoreflect.FileDescriptor

var file_Mysql_Options_MysqlOptions_proto_rawDesc = []byte{
	0x0a, 0x20, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x2f, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f,
	0x4d, 0x79, 0x73, 0x71, 0x6c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x0b, 0x0a, 0x09, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x0d,
	0x0a, 0x0b, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x74, 0x0a,
	0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x31, 0x0a, 0x09, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x4d, 0x79, 0x73, 0x71,
	0x6c, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x22, 0xe0, 0x01, 0x0a, 0x0c, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x52, 0x6f, 0x77, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x52, 0x6f, 0x77, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x2c, 0x0a, 0x06,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4d,
	0x79, 0x73, 0x71, 0x6c, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x52, 0x06, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x74, 0x0a, 0x0a, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x41, 0x75, 0x74, 0x6f, 0x49, 0x6e, 0x63, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x41, 0x75, 0x74, 0x6f, 0x49, 0x6e, 0x63, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73,
	0x4e, 0x55, 0x4c, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x49, 0x73, 0x4e, 0x55,
	0x4c, 0x4c, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2a, 0x3d, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x54, 0x5f, 0x50, 0x4b, 0x49, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x5f,
	0x46, 0x54, 0x49, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x5f, 0x55, 0x49, 0x49, 0x10, 0x03,
	0x12, 0x09, 0x0a, 0x05, 0x54, 0x5f, 0x4e, 0x49, 0x49, 0x10, 0x04, 0x42, 0xa3, 0x01, 0x0a, 0x1b,
	0x68, 0x66, 0x64, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x6d, 0x79,
	0x73, 0x71, 0x6c, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x09, 0x50, 0x42, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x01, 0x5a, 0x4a, 0x64, 0x65, 0x76, 0x2e, 0x70, 0x68,
	0x6f, 0x65, 0x6e, 0x69, 0x78, 0x2d, 0x65, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x61, 0x6f,
	0x6e, 0x61, 0x6e, 0x6b, 0x61, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x68, 0x66, 0x64,
	0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x70, 0x62, 0x2f, 0x6d, 0x79, 0x73, 0x71, 0x6c,
	0x2f, 0x70, 0x62, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3b, 0x70, 0x62, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0xf8, 0x01, 0x01, 0xa2, 0x02, 0x09, 0x50, 0x42, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0xaa, 0x02, 0x1b, 0x48, 0x66, 0x64, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Mysql_Options_MysqlOptions_proto_rawDescOnce sync.Once
	file_Mysql_Options_MysqlOptions_proto_rawDescData = file_Mysql_Options_MysqlOptions_proto_rawDesc
)

func file_Mysql_Options_MysqlOptions_proto_rawDescGZIP() []byte {
	file_Mysql_Options_MysqlOptions_proto_rawDescOnce.Do(func() {
		file_Mysql_Options_MysqlOptions_proto_rawDescData = protoimpl.X.CompressGZIP(file_Mysql_Options_MysqlOptions_proto_rawDescData)
	})
	return file_Mysql_Options_MysqlOptions_proto_rawDescData
}

var file_Mysql_Options_MysqlOptions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Mysql_Options_MysqlOptions_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Mysql_Options_MysqlOptions_proto_goTypes = []interface{}{
	(Type)(0),            // 0: Mysql.Options.Type
	(*MysqlFile)(nil),    // 1: Mysql.Options.MysqlFile
	(*MysqlMethod)(nil),  // 2: Mysql.Options.MysqlMethod
	(*Index)(nil),        // 3: Mysql.Options.Index
	(*MysqlMessage)(nil), // 4: Mysql.Options.MysqlMessage
	(*MysqlService)(nil), // 5: Mysql.Options.MysqlService
	(*MysqlField)(nil),   // 6: Mysql.Options.MysqlField
}
var file_Mysql_Options_MysqlOptions_proto_depIdxs = []int32{
	0, // 0: Mysql.Options.Index.IndexType:type_name -> Mysql.Options.Type
	3, // 1: Mysql.Options.MysqlMessage.Indexs:type_name -> Mysql.Options.Index
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Mysql_Options_MysqlOptions_proto_init() }
func file_Mysql_Options_MysqlOptions_proto_init() {
	if File_Mysql_Options_MysqlOptions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Mysql_Options_MysqlOptions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MysqlFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mysql_Options_MysqlOptions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MysqlMethod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mysql_Options_MysqlOptions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Index); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mysql_Options_MysqlOptions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MysqlMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mysql_Options_MysqlOptions_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MysqlService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Mysql_Options_MysqlOptions_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MysqlField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Mysql_Options_MysqlOptions_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Mysql_Options_MysqlOptions_proto_goTypes,
		DependencyIndexes: file_Mysql_Options_MysqlOptions_proto_depIdxs,
		EnumInfos:         file_Mysql_Options_MysqlOptions_proto_enumTypes,
		MessageInfos:      file_Mysql_Options_MysqlOptions_proto_msgTypes,
	}.Build()
	File_Mysql_Options_MysqlOptions_proto = out.File
	file_Mysql_Options_MysqlOptions_proto_rawDesc = nil
	file_Mysql_Options_MysqlOptions_proto_goTypes = nil
	file_Mysql_Options_MysqlOptions_proto_depIdxs = nil
}
